#!/bin/sh
# vim: ft=sh: sw=2:

unset FORCE

main () {
  parse_command_line "${@}"

  root=`git ws 2>&5` || {
    error "Not a git workspace: `pwd`"
    exit 2
  }

  [ "${FORCE}" = yes ] || info "Simulation mode (dry-run), use --force for normal run"

  cd "${root}" && {
    run git worktree prune

    git branch | grep -v '^[*]' | while read line; do
      make_worktree ${line} || break
    done
  }
}

process_option () {
  option=${1}
  argument=${2}

  case "${option}" in
    *)
      process_standard_option "${@}"
    ;;
  esac
}

usage_and_exit () {
  [ "${2:+set}" = set ] && error "${2}"

  usage "[--help | -h][--force | -f][--dry-run | -n]"
  exit "${1}"
}

make_worktree () {
  top=${1}/src

  [ -e "${top}" ] && {
    warning "Already exists: ${top}"
    return 0
  }

  run git worktree add "${top}" "${1}"
}

. `type "${0}" | awk '{print $(NF)}' | xargs dirname`/ws-sh.lib
