#!/bin/sh
# vim: ft=sh: sw=2:
# Author: Gennady Bystritsky (bystr@mac.com)

LOCATION_MARKER=scripts/hooks/../../config/dot-gitloader

main () {
  unset O_FOLDER O_EXCLUDE

  disable_dry_run
  parse_command_line "${@}"
}

process_parameters () {
  setup_git_environment

  folder=`full_folder_path "${O_FOLDER}"` || {
    error "Not a folder" "\"${O_FOLDER}\""
    exit 2
  }

  [ "${#}" -eq 0 ] && enable_dry_run
  info "Processing ${folder}"

  find_workspaces "${folder}" | while read folder; do
    unless_in_exclude "${folder}" && {
      run git -C "${folder}" "${@}"
    }
  done

  return 0
}

unless_in_exclude () {
  for item in ${O_EXCLUDE}; do
    case "${1}" in
      *${item}*)
        return 1
      ;;
    esac
  done

  return 0
}

find_workspaces () {
  find "${@:-.}" -type d -exec test -d {}/.git \; -prune -exec test -f "{}/${LOCATION_MARKER}" \; -print
}

process_option () {
  option=${1}
  argument=${2}

  case "${option}" in
    --directory | -d )
      O_FOLDER="${argument}"
      return 4
    ;;

    --exclude | -e )
      O_EXCLUDE="${argument} ${O_EXCLUDE}"
      return 4
    ;;

    *)
      process_standard_option "${@}"
    ;;
  esac
}

options_usage () {
  echo "`standard_options_usage`[--directory|-d <folder>][--exclude|-e <pattern>"
}

. `type "${0}" | sed 's/^.* //' | xargs dirname`/core.lib.sh
start import=git "${@}"
