#!/bin/sh
# vim: ft=sh: sw=2:
# Author: Gennady Bystritsky (bystr@mac.com)

DESCEND=yes
LIST=no

unset OFFSET SAFE

main () {
  parse_command_line "${@}"
  setup_git_environment

  ROOT=`git ws 2>&5` || ROOT=`git -C "${script_folder}" ws` || {
    return 2
  }

  [ "${matchers:-no}" = no -a "${LIST}" = no ] && {
    echo "${ROOT}"
    return 0
  }

  [ "${DESCEND}" = yes ] && {
    OFFSET=`git from-top 2>&5`
  }

  cd "${ROOT}" || exit "${?}"

  available=`collect_available`
  matching=`output_filtered yes 1 '' ${available}`

  [ "${LIST}" = yes ] && {
    output_filtered no 1 '' ${matching}
    return 0
  }

  set -- ${matching}

  case ${#} in
    1)
      target=`branch_to_worktree "${1}"`

      [ "${OFFSET:-./}" = ./ ] || {
        deep_target=`echo "${target}/${OFFSET}" | sed 's%/$%%'`
        [ -d "${deep_target}" ] && {
          output 1 "${deep_target}"
          return 0
        }
      }

      output 1 "${target}"
      return 0
    ;;

    0)
      error 'No branches for matchers' ${matchers}
      info 'Available branches:'
      output_filtered no 2 '  ' ${available}
    ;;

    *)
      error 'Ambiguous branches for matchers' ${matchers}
      info 'Matching branches:'
      output_filtered no 2 '  ' ${matching}
    ;;
  esac

  [ "${SAFE}" = yes ] && output 1 .
  return 3
}

output_filtered () {
  filter=${1}
  stream=${2}
  indent=${3}

  shift 3

  for item in "${@}"; do
    [ "${filter}" = no ] || check_match "${item}" && {
      output "${stream}" "${indent}${item}"
    }
  done
}

collect_available () {
  branches_without_worktrees | sort
}

check_match () {
  for matcher in ${matchers}; do
    case "${1}" in
      *${matcher}* )
        continue
      ;;
    esac

    return 1
  done

  return 0
}

process_option () {
  option=${1}
  argument=${2}

  case "${option}" in
    --top | -t )
      DESCEND=no
    ;;

    --list | -l )
      LIST=yes
    ;;

    --safe | -s )
      SAFE=yes
    ;;

    *)
      process_standard_option "${@}"
    ;;
  esac
}

process_parameters () {
  matchers="${@}"
}

options_usage () {
  echo "`standard_options_usage` [--top|-t][--list|-l][--safe|-s][<matcher>...]"
}

. `type "${0}" | awk '{print $(NF)}' | xargs dirname`/core.sh.lib
start import=git,ws "${@}"
