#!/bin/sh
# vim: ft=sh: sw=2:
# Author: Gennady Bystritsky (bystr@mac.com)

main () {
  parse_command_line "${@}"

  ensure_git_workspace
  report_simulation_mode

  run git worktree prune

  git branch | grep -v '^[*]' | while read line; do
    make_worktree ${line} || break
  done
}

make_worktree () {
  top=${1}/src

  [ -e "${top}" ] && {
    warning "Already exists: ${top}"
    return 0
  }

  run git worktree add "${top}" "${1}"
}

process_option () {
  option=${1}
  argument=${2}

  case "${option}" in
    *)
      process_standard_option "${@}"
    ;;
  esac
}

process_parameters () {
  return ${#}
}

options_usage () {
  echo "`standard_options_usage`"
}

. `type "${0}" | awk '{print $(NF)}' | xargs dirname`/core.sh.lib
start import=ws "${@}"
