#!/bin/sh
# vim: ft=sh: sw=2:
# Author: Gennady Bystritsky (bystr@mac.com)

REMOTE=no
MERGE=yes
PUSH=no
EXPLICIT_PUSH=no

main () {
  parse_command_line "${@}"
  setup_git_environment

  ensure_git_workspace
  report_simulation_mode

  [ "${REMOTE}" = yes ] && {
    run git remote update --prune
    ensure_simulation_mode
  }

  is_simulation_mode && {
    MERGE=yes
    PUSH=yes
  }

  git tt top 2>&5 | while read top; do
    cd "${top}" && sync_branch
  done
}

local_with_remote_if_current_and_differ () {
  git bbs "${@}" | awk '$1 == "*" {print $(2), $(3), $(NF)}'
}

sync_branch () {
  set -- `local_with_remote_if_current_and_differ --no-color`
  [ ${#} -ne 3 ] && return

  reason=${2}
  local_no_color=${1}
  remote_no_color=${3}

  set -- `local_with_remote_if_current_and_differ --color`
  [ ${#} -ne 3 ] && return

  local_color=${1}
  remote_color=${3}

  pwd="pwd"

  upstream=`git rev-parse --abbrev-ref @{u} 2>&5` || {
    reason=`echo "${reason}" | tr '[a-z]' '[A-Z]'`

    "${pwd}"
    indent_output_from warning 'Not a valid upstream' "${local_no_color}" "${reason}" "${remote_color}"
    pwd="true"

    return
  }

  [ "${upstream}" != "${remote_no_color}" ] && {
    "${pwd}"
    indent_output_from warning 'Ustream mismatch' "${local_no_color}" "${upstream}" "${remote_color}"
    pwd="true"
  }

  [ "${PUSH}" = yes ] && {
    ensure_no_local_changes || {
      number=`make_number_label "${?}"`

      is_simulation_mode && [ "${EXPLICIT_PUSH}" = no ] && {
        warning 'Specify option --push (-p) for push action at normal run'
        EXPLICIT_PUSH=yes # just to print the above message once
      }

      "${pwd}"
      indent_output_from push "${number}" "${local_color}" "${remote_color}"
      pwd="true"
    }
  }

  [ "${MERGE}" = yes ] && {
    ensure_no_remote_changes || {
      number=`make_number_label "${?}"`
      "${pwd}"

      indent_output_from merge_if_clean "${number}" "${local_color}" "${remote_color}"
      pwd="true"
    }
  }
}

make_number_label () {
  label="${1}"

  [ "${label}" -gt 99 ] && {
    label="99+"
  }

  echo "${label}"
}

ensure_no_remote_changes () {
  return `number_of_revisions ..@{u}`
}

ensure_no_local_changes () {
  return `number_of_revisions @{u}..`
}

number_of_revisions () {
  git log --oneline "${@}" | head -100 | wc -l
}

ensure_clean_workspace () {
  return `git -c color.status=always status -s 2>&1 | tee /dev/stderr | head -100 | wc -l`
}

merge_if_clean () {
  info "${2} <=[${1}] ${3}"

  ensure_clean_workspace || {
    warning "Detected ${?} changed or untracked, not merging."
    return 2
  }

  run git merge --ff-only
}

push () {
  info "${2} [${1}]=> ${3}"
  run git push
}

process_option () {
  debug "O" "${1} (${2})"

  option=${1}
  argument=${2}

  case "${option}" in
    --remote | -r )
      REMOTE=yes
      disable_simulation_mode
    ;;

    --push | -p )
      EXPLICIT_PUSH=yes
      PUSH=yes
      MERGE=no
    ;;

    --merge | -m )
      MERGE=yes
    ;;

    *)
      process_standard_option "${@}"
    ;;
  esac
}

process_parameters () {
  return ${#}
}

options_usage () {
  echo "`standard_options_usage`[--remote|-r][--push|-p][--merge|-m]"
}

. `type "${0}" | awk '{print $(NF)}' | xargs dirname`/core.sh.lib
start import=ws,git "${@}"
