#!/bin/sh
# vim: ft=sh: sw=2:
# Author: Gennady Bystritsky (bystr@mac.com)

main () {
  disable_simulation_mode
  setup_git_environment

  __git_exec__=exec
  git "${@}"
}

git () {
  __git__ ${__git_exec__} "${SK_GIT_REAL:?}" -c include.path="${SK_GIT_ALIASES:?}" "${@}"
}

__git__() {
  [ "${DEBUG}" = yes ] && output 2 == "${@}"
  "${@}"
}

setup_git_environment () {
  unset __git_ws_root__

  ensure_git_real
  ensure_git_aliases
}

from_ws_root () {
  for item in "${@}"; do
    echo "${__git_ws_root__}/${item}"
  done
}

figure_ws_root_unless_set () {
  [ "${1:+set}" = set ] && return 1
  [ "${__git_ws_root__:+set}" = set ] && return 0

  for marker in ${script_folder}/{.,..,../..,../../..}/.git; do
    [ -d "${marker}" ] && {
      __git_ws_root__=`echo "${marker}" | convert_input_to_full_path | xargs dirname`
      return 0
    }
  done

  error 'No workspace root'
  exit 2
}

ensure_git_real () {
  figure_ws_root_unless_set "${SK_GIT_REAL}" || return
  hook=`from_ws_root scripts/hooks/git`

  for item in `find_in_path git`; do
    [ "${item}" != "${hook}" ] && {
      SK_GIT_REAL=${item}
      git=${hook}

      export SK_GIT_REAL git
      return
    }

    shift
  done

  error 'No real git in PATH'
  exit 2
}

find_in_path () {
  for folder in `echo "${PATH}" | sed 's/:/ /g'`; do
    path=${folder}/${1}

    [ "${path:+set}" = set -a -x "${path}" ] && {
      echo "${path}" | convert_input_to_full_path
    }
  done
}

ensure_git_aliases () {
  figure_ws_root_unless_set "${SK_GIT_ALIASES}" || return
  aliases=`from_ws_root config/dot-gitaliases`

  [ -f "${aliases}" ] && {
    SK_GIT_ALIASES=${aliases} export SK_GIT_ALIASES
    return
  }

  error "Missing git aliases: ${aliases:-'???'}"
  exit 3
}

. `type "${0}" | awk '{print $(NF)}' | xargs dirname`/../core.sh.lib
start import=../git "${@}"
