#!/bin/sh
# vim: ft=sh: sw=2:
# Author: Gennady Bystritsky (bystr@mac.com)

main () {
  disable_dry_run
  setup_git_environment

  __git_exec__=exec
  git "${@}"
}

. `type "${0}" | awk '{print $(NF)}' | xargs dirname`/../core.sh.lib
start import=../git "${@}"
